<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\UploadedFile;


class PrototypeController extends Controller
{
    public function beforeAction($action)
    {
        if( Yii::$app->getUser()->isGuest ){
            return $this->redirect('/login/', 302)->send();
        }

        # If user is authorized and trying to go into admin section
        if( (strpos(Url::current(), '/admin/') === 0 || strpos(Url::current(), '/login/') === 0 || strpos(Url::current(), '/index/') === 0)
	        && !Yii::$app->user->can('adminWork')
	        && !Yii::$app->request->isAjax ){
            return $this->redirect('/terminal/calendar/', 302)->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
   


    /**
     * Save model
     *
     * @param $model
     *
     * @throws \Exception
     */
    public function saveModel($model)
    {
        if( empty($model) ){
            throw new \Exception('Empty model');
        }

        $model->UPLOAD = UploadedFile::getInstance($model, 'UPLOAD');
        if( $model->UPLOAD ){
            $fileName = $model->UPLOAD->baseName . '.' . $model->UPLOAD->extension;

            $newImgDir = Yii::$app->params['filesUploadUrl'] . $model::tableName() . '/' . substr(md5($fileName), 0, 5) . '/';
            $newFileDir = Yii::getAlias('@webroot') . $newImgDir;
            $newFilePath = $newFileDir . $fileName;

            if( !is_dir($newFileDir) ){
                mkdir($newFileDir, 0777, true);
            }

            if( $model->UPLOAD->saveAs($newFilePath)
                &&  Image::thumbnail($newFilePath, 300, 300)->save($newFilePath, ['quality' => 70]) ) {
                $model->IMAGE = $newImgDir . $fileName;
            }
            $model->UPLOAD = null;
        }
        
        if( $model->validate() ){
            $model->save();
            return true;
        }
        else{
            return false;
        }
    }
}
